### ISSUE TITLE
invokeTransferFrom() is problem in erc20 example

### ISSUE THREAD

**Issue by TedKang** [s7techlab/cckit#27]
Hi, I ran the erc20 example and it seems to be a problem with invokeTransferFrom().

`allowance, err := getAllowance(c, fromMspId, fromCertId, invoker.GetMSPID(), invoker.GetID())`

In the above code, the argument value corresponding to 'from' and the argument value position of 'invoker' seem to be reversed.

Please confirm.

Thanks

**Comment by vitiko** [comment]
```php
// getAllowance gets amount of token allowed by wallet owner to spend by spender
func getAllowance(c r.Context, ownerMspId, ownerCertId, spenderMspId, spenderCertId string) (int, error) {
	return c.State().GetInt(allowanceKey(ownerMspId, ownerCertId, spenderMspId, spenderCertId), 0)
}
```

in the `invokeTransferFrom()` function  
* `invoker.GetMSPID()` and  `invoker.GetID()` are spender requisites 
* `fromMspId`, `fromCertId` are wallet owner requisites

**Comment by TedKang** [comment]
> ```
> // getAllowance gets amount of token allowed by wallet owner to spend by spender
> func getAllowance(c r.Context, ownerMspId, ownerCertId, spenderMspId, spenderCertId string) (int, error) {
> 	return c.State().GetInt(allowanceKey(ownerMspId, ownerCertId, spenderMspId, spenderCertId), 0)
> }
> ```
> 
> in the `invokeTransferFrom()` function
> 
> * `invoker.GetMSPID()` and  `invoker.GetID()` are spender requisites
> * `fromMspId`, `fromCertId` are wallet owner requisites

you're right. I mean, it would be the token owner to `invoke transferFrom()` in the code above. So I think the Invoker's MspId should be placed in ownerMspId when calling `getAllowance ()`.

<What i understood...>
in the `invokeTransferFrom()` function

- `invoker.GetMSPId()`, `invoker.GetId()` >> token owner
- `fromMspId`, `fromCertId` >> token Sender

Please reply if I misunderstand.

**Comment by vitiko** [comment]
`invokeTransferFrom()` is invoked not by token owner, but by **spender**, who have allowance to spend some amount from token owner, so:

* invoker.GetMSPId(), invoker.GetId() -   **spender**
* fromMspId, fromCertId -  **owner** 
* toMspId, toCertId -  **recipient** 

you can see example in test https://github.com/s7techlab/cckit/blob/master/examples/erc20/erc20_test.go#L101

**Comment by TedKang** [comment]
@vitiko Thanks for answer.
I misunderstood the concept.
