### ISSUE TITLE
Couple Of Questions !

### ISSUE THREAD

**Issue by esumit** [s7techlab/cckit#3]
Thanks for the wonderful work !

Q1. Where is main function in this program ?https://gist.github.com/vitiko/ca8ec2631e3978fcdaa3a237b4c4b43d#file-cars_chaincode_example-go 

Q-2 : Is Owner really important ?

Q-3. I tried to use this , but received on following : return t.router.Handle(stub) on Invoke
2018–09–04 06:09:15.443 UTC [grpc] Printf -> DEBU 006 pickfirstBalancer: HandleSubConnStateChange: 0xc4203c5270, CONNECTING
2018–09–04 06:09:15.444 UTC [grpc] Printf -> DEBU 007 pickfirstBalancer: HandleSubConnStateChange: 0xc4203c5270, READY
panic: runtime error: invalid memory address or nil pointer dereference
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8cac06]

Q-4: On init can we remove it : return owner.SetFromCreator(cc.router.Context(`init`, stub)) and keep return shim.Success(nil) ?

Q-5 : How to Debug it with breakpoint , it without creating HLF network and deploying there ?

Q-6 : Can you send running full program without owner ? and with main included too.

**Comment by vitiko** [comment]
Thanks for your questions! I have added code examples to github repo and to Medium article

Q1: https://github.com/s7techlab/cckit/tree/master/examples/cars/bin/cars 

Q2: Owner extension provides basic access control for chaincode functions, this simplifies the implementation of “user permissions”.

Q4: yes

Q5: https://github.com/s7techlab/cckit/blob/master/examples/cars/cars_noacces_control.go and https://github.com/s7techlab/cckit/tree/master/examples/cars/bin/cars_noac

**Comment by esumit** [comment]
Thank you @vitiko , Great Help @vitiko
