### ISSUE TITLE
NULL characters appearing in CouchDB when using composite keys

### ISSUE THREAD

**Issue by czar0** [s7techlab/cckit#50]
Hi,

I noticed that when using the `Key()` interface for user-defined structs, the objects get stored in the CouchDB state with some Unicode NULL characters.

Example:
```
 "id": "\u0000ASSET\u00001c730708-70b2-4f99-b4c1-cf6689006e32\u0000",
 "key": "\u0000ASSET\u00001c730708-70b2-4f99-b4c1-cf6689006e32\u0000",
```

This does not happen when the composite key is passed directly as an `[]string`.

**Comment by vadimInshakov** [comment]
This is completely normal. This is how Fabric shim works. Composite keys' namespace + object type + utf8 null + your key + utf8 null again.

**Comment by czar0** [comment]
@vadimInshakov my bad, I haven't noticed this behaviour before while using the `shim`, but reading the doc makes sense:

```	
        // CreateCompositeKey combines the given `attributes` to form a composite
	// key. The objectType and attributes are expected to have only valid utf8
	// strings and should not contain U+0000 (nil byte) and U+10FFFF
	// (biggest and unallocated code point).
	// The resulting composite key can be used as the key in PutState().
	CreateCompositeKey(objectType string, attributes []string) (string, error)
```

I guess it is because they are used as wildcard separators.

```
const (
	minUnicodeRuneValue   = 0            //U+0000
	maxUnicodeRuneValue   = utf8.MaxRune //U+10FFFF - maximum (and unallocated) code point
	compositeKeyNamespace = "\x00"
	emptyKeySubstitute    = "\x01"
)
```
