### ISSUE TITLE
How to ship the lib in a docker env

### ISSUE THREAD

**Issue by chrim5** [s7techlab/cckit#6]
Hello! 
I was playing around with your useful lib and it's indeed pretty supportive in the chaincode development process. It speeds up things rapidly :)

However, I struggled with the deployment of the chaincode including the lib on an example docker environment like https://hyperledger-fabric.readthedocs.io/en/release-1.3/build_network.html#install-instantiate-chaincode. How would you deploy your example s7techlab/cckit/examples/cars to it?

Cheers & Thanks!

**Comment by dimaxgl** [comment]
@chrim5 Hi!
We are using chaincode projects with vendor, which includes current library.

**Comment by progamer71** [comment]
Hello,

I'm a new fabric learner.
Please provide some detail to install and instantiate golang chaincode in docker environment.

my environment
debian version 10.1
fabric version 1.4.3
golang version 1.13.1
