### ISSUE TITLE
Testing with mock data?

### ISSUE THREAD

**Issue by lcvalves** [s7techlab/cckit#62]
Hi! First of all, congratiulations on this kit, it's really helping me out to understand Fabric contracts and its quirks.

However, I couldn't find any documentation on how to perform tests with state mock data. Do the contracts need to be deployed to a HLF network to verify that the written business logic is actually working rather than just relying on test results?

**Comment by vitiko** [comment]
Hi, all [chaincode examples](https://github.com/s7techlab/cckit/tree/master/examples) has tests and mock data, for example [here](https://github.com/s7techlab/cckit/blob/master/examples/cpaper_asservice/service/service_test.go). In the examples all tests performed using [mockstub](https://github.com/s7techlab/cckit/tree/master/testing), the fastest way to check chaincode business logic. After that, you can write integration tests by deploying chaincodes to HLF network.

In my practice most business logic tests can be performed on mockstub, it allows to debug and test much faster than deploying to HLF Network.
