### ISSUE TITLE
Support for Private Data and Unit testing

### ISSUE THREAD

**Issue by govinda-attal** [s7techlab/cckit#7]
Hi Victor, 

Simply marvelous work on this kit. Had few questions on Private Data and Unit testing around same. Are these supported?
Any examples around these?

Best Regards,
Govinda

**Comment by vitiko** [comment]
Hi, thank you!  Currently in [mockstub](https://github.com/hyperledger/fabric/blob/release-1.4/core/chaincode/shim/mockstub.go#L158) implemented only few chaincode API methods for working with Private Data (GetPrivateData, PuttPrivateData). CCKit does not support data conversion when working with private data yet

**Comment by govinda-attal** [comment]
This is helpful! Thanks
